import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANGUAGE_KEY = 'agriflow_language';

const DICTIONARY = {
  "en": {
    "Home": "Home",
    "Farm": "Farm",
    "AI": "AI",
    "More": "More",
    "Crop Scanner": "Crop Scanner",
    "AI Chat": "AI Chat",
    "Overview": "Overview",
    "Soil & Water": "Soil & Water",
    "Crop History": "Crop History",
    "Farmer": "Farmer",
    "Rahul Desai": "Rahul Desai",
    "Alex Mercer": "Alex Mercer",
    "Farm Operations Manager": "Farm Operations Manager",
    "My Farm": "My Farm",
    "Nagpur, Maharashtra": "Nagpur, Maharashtra",
    "Maharashtra": "Maharashtra",
    "Nagpur": "Nagpur",
    "Day": "Day",
    "of": "of",
    "irrigation": "irrigation",
    "Wheat": "Wheat",
    "Soybean": "Soybean",
    "Cotton": "Cotton",
    "Rice": "Rice",
    "Sugarcane": "Sugarcane",
    "Tomato": "Tomato",
    "Onion": "Onion",
    "Maize": "Maize",
    "Chilli": "Chilli",
    "Groundnut": "Groundnut",
    "Banana": "Banana",
    "Grapes": "Grapes",
    "Other": "Other",
    "Custom Crop": "Custom Crop",
    "Drip": "Drip",
    "Water efficient, targeted": "Water efficient, targeted",
    "Sprinkler": "Sprinkler",
    "Overhead spray coverage": "Overhead spray coverage",
    "Flood": "Flood",
    "Traditional surface flooding": "Traditional surface flooding",
    "Rain-fed": "Rain-fed",
    "Depends on rainfall": "Depends on rainfall",
    "Furrow": "Furrow",
    "Row-based channel system": "Row-based channel system",
    "Borewell": "Borewell",
    "Groundwater extraction": "Groundwater extraction",
    "Black Soil": "Black Soil",
    "Red Soil": "Red Soil",
    "Sandy Soil": "Sandy Soil",
    "Loamy Soil": "Loamy Soil",
    "Clay Soil": "Clay Soil",
    "Alluvial Soil": "Alluvial Soil",
    "Well": "Well",
    "Canal": "Canal",
    "River": "River",
    "Rainwater": "Rainwater",
    "Tank": "Tank",
    "Low": "Low",
    "Medium": "Medium",
    "High": "High",
    "Local APMC / Mandi": "Local APMC / Mandi",
    "Sell to local wholesale market": "Sell to local wholesale market",
    "Contract Farming": "Contract Farming",
    "Pre-agreed corporate buyer": "Pre-agreed corporate buyer",
    "Direct to Consumer": "Direct to Consumer",
    "Sell directly to local buyers": "Sell directly to local buyers",
    "Acres": "Acres",
    "Hectares": "Hectares",
    "Register Your Crop": "Register Your Crop",
    "Select the crop you are currently growing": "Select the crop you are currently growing",
    "Choose Your Crop": "Choose Your Crop",
    "Crop Details": "Crop Details",
    "Sunlight: Full Sun": "Sunlight: Full Sun",
    "Water Req: Medium": "Water Req: Medium",
    "Growth Stages": "Growth Stages",
    "Standard lifecycle": "Standard lifecycle",
    "days": "days",
    "📅 Expected Harvest:": "📅 Expected Harvest:",
    "Skip for now →": "Skip for now →",
    "Custom Crop Name *": "Custom Crop Name *",
    "Variety / Name": "Variety / Name",
    "Field / Block Name": "Field / Block Name",
    "Farm Location": "Farm Location",
    "Farm Address *": "Farm Address *",
    "Area Allocation": "Area Allocation",
    "Total farm": "Total farm",
    "Acreage for": "Acreage for",
    "Irrigation System": "Irrigation System",
    "Sowing Schedule": "Sowing Schedule",
    "Sowing Date *": "Sowing Date *",
    "Additional Notes": "Additional Notes",
    "Select a crop to continue": "Select a crop to continue",
    "Register": "Register",
    "Data": "Data",
    "1. Farm Setup": "1. Farm Setup",
    "Register your land details": "Register your land details",
    "Basic Info": "Basic Info",
    "Location": "Location",
    "State *": "State *",
    "Map updates automatically based on your address": "Map updates automatically based on your address",
    "Save Farm & Continue to Crop →": "Save Farm & Continue to Crop →",
    "Farm Name *": "Farm Name *",
    "Total Area *": "Total Area *",
    "Address Line 1": "Address Line 1",
    "District *": "District *",
    "Village/Town": "Village/Town",
    "Soil Type *": "Soil Type *",
    "Water Availability": "Water Availability",
    "Primary Water Source": "Primary Water Source",
    "Preferred Market *": "Preferred Market *",
    "AgriFlow": "AgriFlow",
    "Welcome back": "Welcome back",
    "Sign in to manage your farm's performance.": "Sign in to manage your farm's performance.",
    "Forgot password?": "Forgot password?",
    "Don't have an account?": "Don't have an account?",
    "Login ->": "Login ->",
    "Mobile Number": "Mobile Number",
    "Password or OTP": "Password or OTP",
    "← Back": "← Back",
    "Create Account": "Create Account",
    "Join thousands of smart farmers": "Join thousands of smart farmers",
    "Already have an account?": "Already have an account?",
    "Sign In": "Sign In",
    "Farmer Name *": "Farmer Name *",
    "Mobile Number *": "Mobile Number *",
    "Location *": "Location *",
    "Password / OTP": "Password / OTP",
    "Overall Farm Health": "Overall Farm Health",
    "Weather Context": "Weather Context",
    "Quick Actions": "Quick Actions",
    "Today's Actions": "Today's Actions",
    "VIEW ALL": "VIEW ALL",
    "Progress": "Progress",
    "Details →": "Details →",
    "Register your crop to get personalized insights": "Register your crop to get personalized insights",
    "Scan Crop": "Scan Crop",
    "Farm Sensors": "Farm Sensors",
    "Add Expense": "Add Expense",
    "Add Income": "Add Income",
    "Daily Life": "Daily Life",
    "Life Cycle": "Life Cycle",
    "Good Morning": "Good Morning",
    "Good Afternoon": "Good Afternoon",
    "Good Evening": "Good Evening",
    "Farm Health": "Farm Health",
    "Health": "Health",
    "Growth": "Growth",
    "Water": "Water",
    "Disease Risk": "Disease Risk",
    "Good": "Good",
    "Excellent": "Excellent",
    "Humidity": "Humidity",
    "Rain": "Rain",
    "km/h": "km/h",
    "Partly Cloudy": "Partly Cloudy",
    "Sunny": "Sunny",
    "Rainy": "Rainy",
    "Cloudy": "Cloudy",
    "Stormy": "Stormy",
    "Clear": "Clear",
    "Crop Progress": "Crop Progress",
    "Sowing": "Sowing",
    "Harvest": "Harvest",
    "Growth Performance": "Growth Performance",
    "Stage": "Stage",
    "Germination": "Germination",
    "Tillering": "Tillering",
    "Heading": "Heading",
    "Maturation": "Maturation",
    "Vegetative": "Vegetative",
    "Flowering": "Flowering",
    "Pod Formation": "Pod Formation",
    "Squaring": "Squaring",
    "Boll Formation": "Boll Formation",
    "Nursery": "Nursery",
    "Transplanting": "Transplanting",
    "Panicle Initiation": "Panicle Initiation",
    "Planting": "Planting",
    "Grand Growth": "Grand Growth",
    "Fruit Set": "Fruit Set",
    "Bulb Formation": "Bulb Formation",
    "Tasseling": "Tasseling",
    "Silking": "Silking",
    "Pegging": "Pegging",
    "Pod Fill": "Pod Fill",
    "Shooting": "Shooting",
    "Bunch Development": "Bunch Development",
    "Pruning": "Pruning",
    "Budbreak": "Budbreak",
    "Shoot Growth": "Shoot Growth",
    "Veraison": "Veraison",
    "Ask AgriFlow AI...": "Ask AgriFlow AI...",
    "Thinking...": "Thinking...",
    "Suggested Questions": "Suggested Questions",
    "AI Crop Scanner": "AI Crop Scanner",
    "Scan Your Crop": "Scan Your Crop",
    "Take or upload a photo of your crop to detect diseases with AI": "Take or upload a photo of your crop to detect diseases with AI",
    "Analyzing crop...": "Analyzing crop...",
    "AI is examining your crop for diseases": "AI is examining your crop for diseases",
    "Scan Results": "Scan Results",
    "Take Photo": "Take Photo",
    "Upload Image": "Upload Image",
    "Upload": "Upload",
    "Loading...": "Loading...",
    "Upload / Take Photo": "Upload / Take Photo",
    "✕ Remove": "✕ Remove",
    "Camera": "Camera",
    "Gallery": "Gallery",
    "Live Analysis": "Live Analysis",
    "Analysis Result": "Analysis Result",
    "Disease Detected": "Disease Detected",
    "Leaf Blight": "Leaf Blight",
    "Confidence": "Confidence",
    "Severity": "Severity",
    "Action Plan": "Action Plan",
    "Fertilizer Recommendation": "Fertilizer Recommendation",
    "Precautions": "Precautions",
    "+ Add to Field Log": "+ Add to Field Log",
    "Recent Scans": "Recent Scans",
    "Field B - Corn": "Field B - Corn",
    "Healthy • 2h ago": "Healthy • 2h ago",
    "Yield Prediction": "Yield Prediction",
    "Upcoming Tasks": "Upcoming Tasks",
    "Recent Activities": "Recent Activities",
    "+ Register a Crop": "+ Register a Crop",
    "No tasks yet. Add tasks to your farm diary.": "No tasks yet. Add tasks to your farm diary.",
    "No recent activities recorded.": "No recent activities recorded.",
    "Register a crop to see yield prediction.": "Register a crop to see yield prediction.",
    "Language Settings": "Language Settings",
    "Finance & Yield": "Finance & Yield",
    "Farm Logistics": "Farm Logistics",
    "Intelligence & AI": "Intelligence & AI",
    "System Hardware": "System Hardware",
    "Select Language": "Select Language",
    "Choose your preferred language": "Choose your preferred language",
    "Save Language": "Save Language",
    "Continue": "Continue",
    "You can change this later in Settings": "You can change this later in Settings",
    "Expense Type *": "Expense Type *",
    "Amount & Date": "Amount & Date",
    "Payment Details": "Payment Details",
    "Payment Mode": "Payment Mode",
    "Amount (₹) *": "Amount (₹) *",
    "Date": "Date",
    "Paid To (Payee)": "Paid To (Payee)",
    "Notes (Optional)": "Notes (Optional)",
    "Expenses": "Expenses",
    "Filter": "Filter",
    "Expense Distribution": "Expense Distribution",
    "All Expenses": "All Expenses",
    "Income Type *": "Income Type *",
    "Who & Why": "Who & Why",
    "Purpose / Reason": "Purpose / Reason",
    "Amount": "Amount",
    "💡 Auto-calculate from quantity × price": "💡 Auto-calculate from quantity × price",
    "Calculated Amount": "Calculated Amount",
    "From Whom (Source) *": "From Whom (Source) *",
    "Custom Purpose (Optional)": "Custom Purpose (Optional)",
    "Price/Unit (₹)": "Price/Unit (₹)",
    "Crop Lifecycle": "Crop Lifecycle",
    "Stage Details": "Stage Details",
    "Care Schedule": "Care Schedule",
    "Daily Crop Life": "Daily Crop Life",
    "Select Day (0 – 5)": "Select Day (0 – 5)",
    "Document early germination stages with photos": "Document early germination stages with photos",
    "Today's Conditions": "Today's Conditions",
    "Past Entries": "Past Entries",
    "Temp (°C)": "Temp (°C)",
    "Humidity (%)": "Humidity (%)",
    "Observation Note": "Observation Note",
    "Farm Diary": "Farm Diary",
    "Farm Map": "Farm Map",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Village": "Village",
    "District": "District",
    "Map Legend": "Map Legend",
    "Harvest Planning": "Harvest Planning",
    "Estimated Harvest Date": "Estimated Harvest Date",
    "Harvest Readiness": "Harvest Readiness",
    "Total Estimated Cost": "Total Estimated Cost",
    "Planning Details": "Planning Details",
    "Cost Estimate": "Cost Estimate",
    "Required Machinery": "Required Machinery",
    "Plan Harvest": "Plan Harvest",
    "View Storage Recommendation": "View Storage Recommendation",
    "Smart Irrigation": "Smart Irrigation",
    "Soil Moisture Level": "Soil Moisture Level",
    "Estimated Water Required": "Estimated Water Required",
    "Current Status": "Current Status",
    "AI Recommendation": "AI Recommendation",
    "Actions": "Actions",
    "Schedule Irrigation": "Schedule Irrigation",
    "View Field Map": "View Field Map",
    "Planning & Logistics": "Planning & Logistics",
    "Optimize your upcoming harvest operations and supply chain routes.": "Optimize your upcoming harvest operations and supply chain routes.",
    "Crop Readiness": "Crop Readiness",
    "RESOURCE REQUIREMENTS": "RESOURCE REQUIREMENTS",
    "Labor": "Labor",
    "Duration": "Duration",
    "Required Storage Volume": "Required Storage Volume",
    "LOGISTICS ESTIMATE": "LOGISTICS ESTIMATE",
    "Transport Cost": "Transport Cost",
    "Est. Fuel": "Est. Fuel",
    "Farm Spatial Overview": "Farm Spatial Overview",
    "Loading market data...": "Loading market data...",
    "Market Intelligence": "Market Intelligence",
    "Best Selling Period:": "Best Selling Period:",
    "Price History — Last 6 Months": "Price History — Last 6 Months",
    "Nearby Mandis": "Nearby Mandis",
    "Notifications": "Notifications",
    "Plant Life Cycle": "Plant Life Cycle",
    "General Crop Life Cycle": "General Crop Life Cycle",
    "Typical stages of plant development": "Typical stages of plant development",
    "CURRENT STAGE": "CURRENT STAGE",
    "Expected Yield": "Expected Yield",
    "Total Quintals": "Total Quintals",
    "Risk Level": "Risk Level",
    "Prediction Confidence": "Prediction Confidence",
    "Production Projection": "Production Projection",
    "Influencing Factors": "Influencing Factors",
    "Registration successful!": "Registration successful!",
    "Please enter mobile number and password.": "Please enter mobile number and password.",
    "Login failed. Try again.": "Login failed. Try again.",
    "No data available": "No data available",
    "Loading": "Loading",
    "Save": "Save",
    "Cancel": "Cancel",
    "Back": "Back",
    "Submit": "Submit",
    "Next": "Next",
    "Done": "Done",
    "Welcome to AgriFlow": "Welcome to AgriFlow",
    "Empowering your agricultural journey with AI-driven insights and precision management.": "Empowering your agricultural journey with AI-driven insights and precision management.",
    "Get Started": "Get Started",
    "Log In": "Log In",
    "since sowing": "since sowing",
    "Save Day Entry →": "Save Day Entry →",
    "Saved!": "Saved!",
    "Detection Confidence": "Detection Confidence",
    "Symptoms Detected": "Symptoms Detected",
    "Treatment Options": "Treatment Options",
    "Chemical": "Chemical",
    "Organic": "Organic",
    "Frequency": "Frequency",
    "View Full Report": "View Full Report",
    "Scan Another": "Scan Another",
    "Mark Complete": "Mark Complete",
    "High Priority": "High Priority",
    "Medium Priority": "Medium Priority",
    "Low Priority": "Low Priority",
    "My Crops": "My Crops",
    "+ Add Crop": "+ Add Crop",
    "Select / Switch Crop": "Select / Switch Crop",
    "Please select a crop.": "Please select a crop.",
    "Please enter the acreage for this crop.": "Please enter the acreage for this crop.",
    "Please select an irrigation system.": "Please select an irrigation system.",
    "Please enter the sowing date.": "Please enter the sowing date.",
    "Example": "Example",
    "Full Scan Report": "Full Scan Report",
    "What This Means (In Simple Words)": "What This Means (In Simple Words)",
    "What the AI Noticed on Your Crop": "What the AI Noticed on Your Crop",
    "These are the exact signs the AI detected:": "These are the exact signs the AI detected:",
    "What To Do Right Now": "What To Do Right Now",
    "Follow these simple steps:": "Follow these simple steps:",
    "AI Expert Recommendation": "AI Expert Recommendation",
    "Treatment Options": "Treatment Options",
    "Choose the one that works best for you:": "Choose the one that works best for you:",
    "Chemical Treatment": "Chemical Treatment",
    "Available at any agri store. Fast-acting.": "Available at any agri store. Fast-acting.",
    "Organic / Natural Treatment": "Organic / Natural Treatment",
    "Safer for soil. Slower but eco-friendly.": "Safer for soil. Slower but eco-friendly.",
    "Keep Your Crop Healthy!": "Keep Your Crop Healthy!",
    "Add to Expenses": "Add to Expenses",
    "Receipt / Photo": "Receipt / Photo",
    "✕ Remove Photo": "✕ Remove Photo",
    "Save Day Entry →": "Save Day Entry →",
    "Windy": "Windy",
    "Leaf Blight": "Leaf Blight",
    "Powdery Mildew": "Powdery Mildew",
    "Root Rot": "Root Rot",
    "Bacterial Wilt": "Bacterial Wilt",
    "Healthy Crop": "Healthy Crop",
    "Iron Deficiency": "Iron Deficiency",
    "Moderate": "Moderate",
    "Today’s Mandi Real-Time Rates": "Today’s Mandi Real-Time Rates",
    "Real sales reported by farmers in": "Real sales reported by farmers in",
    "Verified APMC Mandi Trade": "Verified APMC Mandi Trade",
    "All Prices": "All Prices",
    "All Local Trades": "All Local Trades",
    "Did you sell harvest in Mandi today?": "Did you sell harvest in Mandi today?",
    "Record your actual sale to help fellow farmers in": "Record your actual sale to help fellow farmers in",
    "Record Sale": "Record Sale",
    "Record Mandi Harvest Sale": "Record Mandi Harvest Sale",
    "Crop Sold": "Crop Sold",
    "Selling Mandi": "Selling Mandi",
    "Actual Selling Price per kg (₹)": "Actual Selling Price per kg (₹)",
    "Quantity Sold": "Quantity Sold",
    "Submit Real Mandi Trade": "Submit Real Mandi Trade",
    "Your mandi sale has been recorded and shared with nearby farmers!": "Your mandi sale has been recorded and shared with nearby farmers!",
    "Net Farm Savings (शिल्लक बचत)": "Net Farm Savings",
    "Total Incomes (+ जमा)": "Total Incomes (+ Credit)",
    "Total Expenses (- खर्च)": "Total Expenses (- Debit)",
    "Top Expenses Breakdown": "Top Expenses Breakdown",
    "Income Sources Breakdown": "Income Sources Breakdown",
    "All Transactions": "All Transactions",
    "Incomes": "Incomes",
    "Expenses": "Expenses",
    "Log Farm Income": "Log Farm Income",
    "Log Farm Expense": "Log Farm Expense",
    "Save Transaction": "Save Transaction",
    "Active Market": "Active Market",
    "Govt. Regulated": "Govt. Regulated",
    "APMC Mandi Directory": "APMC Mandi Directory",
    "1 hour ago": "1 hour ago",
    "3 hours ago": "3 hours ago",
    "5 hours ago": "5 hours ago",
    "Today, 10:45 AM": "Today, 10:45 AM",
    "Today, 08:30 AM": "Today, 08:30 AM",
    "Today, 09:15 AM": "Today, 09:15 AM",
    "Today, 11:00 AM": "Today, 11:00 AM",
    "Just now": "Just now",
    "Ramtek APMC Mandi": "Ramtek APMC Mandi",
    "Nagpur APMC Mandi (Kalamna)": "Nagpur APMC Mandi (Kalamna)",
    "Hingna APMC Mandi": "Hingna APMC Mandi",
    "Kalmeshwar APMC Mandi": "Kalmeshwar APMC Mandi",
    "Katol APMC Mandi": "Katol APMC Mandi",
    "Saoner APMC Mandi": "Saoner APMC Mandi",
    "Umred APMC Mandi": "Umred APMC Mandi",
    "Mansar, Ramtek": "Mansar, Ramtek",
    "Ramtek": "Ramtek",
    "Saoner": "Saoner",
    "Katol": "Katol",
    "Umred": "Umred"
  },
  "hi": {
    "Home": "होम",
    "Farm": "खेत",
    "AI": "एआई",
    "More": "अधिक",
    "Crop Scanner": "फसल स्कैनर",
    "AI Chat": "एआई चैट",
    "Overview": "अवलोकन",
    "Soil & Water": "मिट्टी और पानी",
    "Crop History": "फसल इतिहास",
    "Farmer": "किसान",
    "Rahul Desai": "राहुल देसाई",
    "Alex Mercer": "एलेक्स मर्सर",
    "Farm Operations Manager": "खेत संचालन प्रबंधक",
    "My Farm": "मेरा खेत",
    "Nagpur, Maharashtra": "नागपुर, महाराष्ट्र",
    "Maharashtra": "महाराष्ट्र",
    "Nagpur": "नागपुर",
    "Day": "दिन",
    "of": "का",
    "irrigation": "सिंचाई",
    "Wheat": "गेहूं",
    "Soybean": "सोयाबीन",
    "Cotton": "कपास",
    "Rice": "चावल",
    "Sugarcane": "गन्ना",
    "Tomato": "टमाटर",
    "Onion": "प्याज",
    "Maize": "मक्का",
    "Chilli": "मिर्च",
    "Groundnut": "मूंगफली",
    "Banana": "केला",
    "Grapes": "अंगूर",
    "Other": "अन्य",
    "Custom Crop": "कस्टम फसल",
    "Drip": "ड्रिप (टपक)",
    "Water efficient, targeted": "पानी बचाने वाली, सटीक",
    "Sprinkler": "स्प्रिंकलर (फुहारा)",
    "Overhead spray coverage": "हवा से छिड़काव",
    "Flood": "बाढ़ (पारंपरिक)",
    "Traditional surface flooding": "पारंपरिक सतह सिंचाई",
    "Rain-fed": "वर्षा आधारित",
    "Depends on rainfall": "बारिश पर निर्भर",
    "Furrow": "नालीदार",
    "Row-based channel system": "पंक्ति आधारित नाली प्रणाली",
    "Borewell": "बोरवेल",
    "Groundwater extraction": "भूजल निष्कर्षण",
    "Black Soil": "काली मिट्टी",
    "Red Soil": "लाल मिट्टी",
    "Sandy Soil": "रेतीली मिट्टी",
    "Loamy Soil": "दोमट मिट्टी",
    "Clay Soil": "चिकनी मिट्टी",
    "Alluvial Soil": "जलोढ़ मिट्टी",
    "Well": "कुआं",
    "Canal": "नहर",
    "River": "नदी",
    "Rainwater": "वर्षा जल",
    "Tank": "तालाब/टंकी",
    "Low": "कम",
    "Medium": "मध्यम",
    "High": "उच्च",
    "Local APMC / Mandi": "स्थानीय मंडी / APMC",
    "Sell to local wholesale market": "स्थानीय थोक बाजार में बेचें",
    "Contract Farming": "कॉन्ट्रैक्ट फार्मिंग",
    "Pre-agreed corporate buyer": "पूर्व-सहमति कॉर्पोरेट खरीदार",
    "Direct to Consumer": "सीधे उपभोक्ता को",
    "Sell directly to local buyers": "स्थानीय खरीदारों को सीधे बेचें",
    "Acres": "एकड़",
    "Hectares": "हेक्टेयर",
    "Register Your Crop": "अपनी फसल दर्ज करें",
    "Select the crop you are currently growing": "वर्तमान में उगाई जा रही फसल चुनें",
    "Choose Your Crop": "अपनी फसल चुनें",
    "Crop Details": "फसल विवरण",
    "Sunlight: Full Sun": "धूप: पूर्ण सूर्यप्रकाश",
    "Water Req: Medium": "पानी आवश्यकता: मध्यम",
    "Growth Stages": "विकास चरण",
    "Standard lifecycle": "मानक जीवन चक्र",
    "days": "दिन",
    "📅 Expected Harvest:": "📅 अपेक्षित कटाई:",
    "Skip for now →": "अभी छोड़ें →",
    "Custom Crop Name *": "कस्टम फसल का नाम *",
    "Variety / Name": "किस्म / नाम",
    "Field / Block Name": "खेत / ब्लॉक का नाम",
    "Farm Location": "खेत का स्थान",
    "Farm Address *": "खेत का पता *",
    "Area Allocation": "क्षेत्र आवंटन",
    "Total farm": "कुल खेत",
    "Acreage for": "रकबा",
    "Irrigation System": "सिंचाई प्रणाली",
    "Sowing Schedule": "बुवाई अनुसूची",
    "Sowing Date *": "बुवाई की तारीख *",
    "Additional Notes": "अतिरिक्त नोट्स",
    "Select a crop to continue": "जारी रखने के लिए फसल चुनें",
    "Register": "पंजीकरण करें",
    "Data": "डेटा",
    "1. Farm Setup": "1. खेत सेटअप",
    "Register your land details": "अपनी जमीन का विवरण दर्ज करें",
    "Basic Info": "बुनियादी जानकारी",
    "Location": "स्थान",
    "State *": "राज्य *",
    "Map updates automatically based on your address": "नक्शा पते के आधार पर अपने आप अपडेट होता है",
    "Save Farm & Continue to Crop →": "खेत सहेजें और फसल जारी करें →",
    "Farm Name *": "खेत का नाम *",
    "Total Area *": "कुल क्षेत्रफल *",
    "Address Line 1": "पता पंक्ति 1",
    "District *": "जिला *",
    "Village/Town": "गाँव / शहर",
    "Soil Type *": "मिट्टी का प्रकार *",
    "Water Availability": "पानी की उपलब्धता",
    "Primary Water Source": "प्राथमिक जल स्रोत",
    "Preferred Market *": "पसंदीदा बाजार *",
    "AgriFlow": "AgriFlow",
    "Welcome back": "वापसी पर स्वागत है",
    "Sign in to manage your farm's performance.": "अपने खेत का प्रदर्शन प्रबंधित करने के लिए साइन इन करें।",
    "Forgot password?": "पासवर्ड भूल गए?",
    "Don't have an account?": "खाता नहीं है?",
    "Login ->": "लॉगिन करें →",
    "Mobile Number": "मोबाइल नंबर",
    "Password or OTP": "पासवर्ड या OTP",
    "← Back": "← वापस",
    "Create Account": "खाता बनाएं",
    "Join thousands of smart farmers": "हजारों स्मार्ट किसानों से जुड़ें",
    "Already have an account?": "पहले से खाता है?",
    "Sign In": "साइन इन",
    "Farmer Name *": "किसान का नाम *",
    "Mobile Number *": "मोबाइल नंबर *",
    "Location *": "स्थान *",
    "Password / OTP": "पासवर्ड / OTP",
    "Overall Farm Health": "कुल खेत का स्वास्थ्य",
    "Weather Context": "मौसम की जानकारी",
    "Quick Actions": "त्वरित कार्य",
    "Today's Actions": "आज के कार्य",
    "VIEW ALL": "सभी देखें",
    "Progress": "प्रगति",
    "Details →": "विवरण →",
    "Register your crop to get personalized insights": "व्यक्तिगत सुझावों के लिए अपनी फसल दर्ज करें",
    "Scan Crop": "फसल स्कैन करें",
    "Farm Sensors": "खेत के सेंसर",
    "Add Expense": "खर्च जोड़ें",
    "Add Income": "आय जोड़ें",
    "Daily Life": "दैनिक जीवन",
    "Life Cycle": "जीवन चक्र",
    "Good Morning": "शुभ प्रभात",
    "Good Afternoon": "शुभ दोपहर",
    "Good Evening": "शुभ संध्या",
    "Farm Health": "खेत का स्वास्थ्य",
    "Health": "स्वास्थ्य",
    "Growth": "विकास",
    "Water": "पानी",
    "Disease Risk": "रोग का जोखिम",
    "Good": "अच्छा",
    "Excellent": "उत्कृष्ट",
    "Humidity": "आर्द्रता",
    "Rain": "बारिश",
    "km/h": "किमी/घंटा",
    "Partly Cloudy": "आंशिक बादल",
    "Sunny": "धूप",
    "Rainy": "बरसात",
    "Cloudy": "बादल",
    "Stormy": "तूफानी",
    "Clear": "साफ",
    "Crop Progress": "फसल की प्रगति",
    "Sowing": "बुवाई",
    "Harvest": "कटाई",
    "Growth Performance": "विकास प्रदर्शन",
    "Stage": "चरण",
    "Germination": "अंकुरण",
    "Tillering": "कल्ले फूटना",
    "Heading": "बाली निकलना",
    "Maturation": "परिपक्वता",
    "Vegetative": "वानस्पतिक",
    "Flowering": "फूल आना",
    "Pod Formation": "फली बनना",
    "Squaring": "कलियां बनना",
    "Boll Formation": "टिंडे बनना",
    "Nursery": "नर्सरी",
    "Transplanting": "रोपाई",
    "Panicle Initiation": "बाली की शुरुआत",
    "Planting": "रोपण",
    "Grand Growth": "तीव्र वृद्धि",
    "Fruit Set": "फल लगना",
    "Bulb Formation": "कंद बनना",
    "Tasseling": "नर मंजरी",
    "Silking": "सिल्किंग",
    "Pegging": "सुइयां बनना",
    "Pod Fill": "फली भरना",
    "Shooting": "निकासी",
    "Bunch Development": "घार का विकास",
    "Pruning": "छंटाई",
    "Budbreak": "कली फूटना",
    "Shoot Growth": "शाखा वृद्धि",
    "Veraison": "रंग बदलना",
    "Ask AgriFlow AI...": "AgriFlow AI से पूछें...",
    "Thinking...": "सोच रहा हूँ...",
    "Suggested Questions": "सुझाए गए प्रश्न",
    "AI Crop Scanner": "AI फसल स्कैनर",
    "Scan Your Crop": "अपनी फसल स्कैन करें",
    "Take or upload a photo of your crop to detect diseases with AI": "AI से बीमारी पहचानने के लिए फसल की फोटो लें या अपलोड करें",
    "Analyzing crop...": "फसल का विश्लेषण हो रहा है...",
    "AI is examining your crop for diseases": "AI आपकी फसल में बीमारियाँ खोज रहा है",
    "Scan Results": "स्कैन परिणाम",
    "Take Photo": "फोटो लें",
    "Upload Image": "छवि अपलोड करें",
    "Upload": "अपलोड करें",
    "Loading...": "लोड हो रहा है...",
    "Upload / Take Photo": "अपलोड करें / फोटो लें",
    "✕ Remove": "✕ हटाएं",
    "Camera": "कैमरा",
    "Gallery": "गैलरी",
    "Live Analysis": "लाइव विश्लेषण",
    "Analysis Result": "विश्लेषण परिणाम",
    "Disease Detected": "बीमारी का पता चला",
    "Leaf Blight": "पत्ती का झुलसा (लीफ ब्लाइट)",
    "Confidence": "आत्मविश्वास",
    "Severity": "गंभीरता",
    "Action Plan": "कार्य योजना",
    "Fertilizer Recommendation": "उर्वरक सिफारिश",
    "Precautions": "सावधानियां",
    "+ Add to Field Log": "+ फील्ड लॉग में जोड़ें",
    "Recent Scans": "हाल के स्कैन",
    "Field B - Corn": "खेत B - मक्का",
    "Healthy • 2h ago": "स्वस्थ • 2 घंटे पहले",
    "Yield Prediction": "उपज का पूर्वानुमान",
    "Upcoming Tasks": "आगामी कार्य",
    "Recent Activities": "हाल की गतिविधियाँ",
    "+ Register a Crop": "+ फसल दर्ज करें",
    "No tasks yet. Add tasks to your farm diary.": "अभी तक कोई कार्य नहीं। डायरी में जोड़ें।",
    "No recent activities recorded.": "कोई हालिया गतिविधि दर्ज नहीं।",
    "Register a crop to see yield prediction.": "उपज पूर्वानुमान देखने के लिए फसल दर्ज करें।",
    "Language Settings": "भाषा सेटिंग",
    "Finance & Yield": "वित्त और उपज",
    "Farm Logistics": "खेत लॉजिस्टिक्स",
    "Intelligence & AI": "बुद्धिमत्ता और एआई",
    "System Hardware": "सिस्टम हार्डवेयर",
    "Select Language": "भाषा चुनें",
    "Choose your preferred language": "अपनी पसंदीदा भाषा चुनें",
    "Save Language": "भाषा सहेजें",
    "Continue": "आगे बढ़ें",
    "You can change this later in Settings": "आप इसे बाद में सेटिंग में बदल सकते हैं",
    "Expense Type *": "खर्च का प्रकार *",
    "Amount & Date": "राशि और तारीख",
    "Payment Details": "भुगतान विवरण",
    "Payment Mode": "भुगतान का तरीका",
    "Amount (₹) *": "राशि (₹) *",
    "Date": "तारीख",
    "Paid To (Payee)": "भुगतानकर्ता को",
    "Notes (Optional)": "नोट्स (वैकल्पिक)",
    "Expenses": "खर्च",
    "Filter": "फ़िल्टर",
    "Expense Distribution": "खर्च वितरण",
    "All Expenses": "सभी खर्च",
    "Income Type *": "आय का प्रकार *",
    "Who & Why": "किसे और क्यों",
    "Purpose / Reason": "उद्देश्य / कारण",
    "Amount": "राशि",
    "💡 Auto-calculate from quantity × price": "💡 मात्रा × कीमत से स्वतः गणना",
    "Calculated Amount": "गणना की गई राशि",
    "From Whom (Source) *": "किससे (स्रोत) *",
    "Custom Purpose (Optional)": "कस्टम उद्देश्य (वैकल्पिक)",
    "Price/Unit (₹)": "कीमत/इकाई (₹)",
    "Crop Lifecycle": "फसल जीवन चक्र",
    "Stage Details": "चरण विवरण",
    "Care Schedule": "देखभाल अनुसूची",
    "Daily Crop Life": "दैनिक फसल जीवन",
    "Select Day (0 – 5)": "दिन चुनें (0 – 5)",
    "Document early germination stages with photos": "फोटो के साथ प्रारंभिक अंकुरण चरण दर्ज करें",
    "Today's Conditions": "आज की स्थितियाँ",
    "Past Entries": "पिछली प्रविष्टियाँ",
    "Temp (°C)": "तापमान (°C)",
    "Humidity (%)": "आर्द्रता (%)",
    "Observation Note": "अवलोकन नोट",
    "Farm Diary": "खेत डायरी",
    "Farm Map": "खेत का नक्शा",
    "Latitude": "अक्षांश",
    "Longitude": "देशांतर",
    "Village": "गाँव",
    "District": "जिला",
    "Map Legend": "नक्शा किंवदंती",
    "Harvest Planning": "कटाई योजना",
    "Estimated Harvest Date": "अनुमानित कटाई की तारीख",
    "Harvest Readiness": "कटाई की तैयारी",
    "Total Estimated Cost": "कुल अनुमानित लागत",
    "Planning Details": "योजना विवरण",
    "Cost Estimate": "लागत अनुमान",
    "Required Machinery": "आवश्यक मशीनरी",
    "Plan Harvest": "कटाई की योजना बनाएं",
    "View Storage Recommendation": "भंडारण सिफारिश देखें",
    "Smart Irrigation": "स्मार्ट सिंचाई",
    "Soil Moisture Level": "मिट्टी की नमी का स्तर",
    "Estimated Water Required": "अनुमानित पानी की आवश्यकता",
    "Current Status": "वर्तमान स्थिति",
    "AI Recommendation": "AI की सिफारिश",
    "Actions": "कार्रवाई",
    "Schedule Irrigation": "सिंचाई अनुसूची बनाएं",
    "View Field Map": "खेत का नक्शा देखें",
    "Planning & Logistics": "योजना और लॉजिस्टिक्स",
    "Optimize your upcoming harvest operations and supply chain routes.": "आगामी कटाई और आपूर्ति श्रृंखला मार्गों को अनुकूलित करें।",
    "Crop Readiness": "फसल तैयारी",
    "RESOURCE REQUIREMENTS": "संसाधन आवश्यकताएं",
    "Labor": "श्रम",
    "Duration": "अवधि",
    "Required Storage Volume": "आवश्यक भंडारण क्षमता",
    "LOGISTICS ESTIMATE": "लॉजिस्टिक्स अनुमान",
    "Transport Cost": "परिवहन लागत",
    "Est. Fuel": "अनुमानित ईंधन",
    "Farm Spatial Overview": "खेत का स्थानिक अवलोकन",
    "Loading market data...": "बाजार डेटा लोड हो रहा है...",
    "Market Intelligence": "बाजार बुद्धिमत्ता",
    "Best Selling Period:": "सबसे अच्छा बिक्री काल:",
    "Price History — Last 6 Months": "मूल्य इतिहास — पिछले 6 महीने",
    "Nearby Mandis": "नजदीकी मंडियाँ",
    "Notifications": "सूचनाएं",
    "Plant Life Cycle": "पौधे का जीवन चक्र",
    "General Crop Life Cycle": "सामान्य फसल जीवन चक्र",
    "Typical stages of plant development": "पौधे के विकास के सामान्य चरण",
    "CURRENT STAGE": "वर्तमान चरण",
    "Expected Yield": "अपेक्षित उपज",
    "Total Quintals": "कुल क्विंटल",
    "Risk Level": "जोखिम स्तर",
    "Prediction Confidence": "पूर्वानुमान विश्वास",
    "Production Projection": "उत्पादन प्रक्षेपण",
    "Influencing Factors": "प्रभावशाली कारक",
    "Registration successful!": "पंजीकरण सफल!",
    "Please enter mobile number and password.": "कृपया मोबाइल नंबर और पासवर्ड दर्ज करें।",
    "Login failed. Try again.": "लॉगिन विफल। पुनः प्रयास करें।",
    "No data available": "कोई डेटा उपलब्ध नहीं",
    "Loading": "लोड हो रहा है",
    "Save": "सहेजें",
    "Cancel": "रद्द करें",
    "Back": "वापस",
    "Submit": "जमा करें",
    "Next": "अगला",
    "Done": "हो गया",
    "Welcome to AgriFlow": "AgriFlow में आपका स्वागत है",
    "Empowering your agricultural journey with AI-driven insights and precision management.": "AI-संचालित अंतर्दृष्टि और सटीक प्रबंधन के साथ आपकी कृषि यात्रा को सशक्त बनाना।",
    "Get Started": "शुरू करें",
    "Log In": "लॉग इन",
    "since sowing": "बुवाई से",
    "Save Day Entry →": "दिन प्रविष्टि सहेजें →",
    "Saved!": "सहेजा गया!",
    "Detection Confidence": "पहचान सटीकता",
    "Symptoms Detected": "पहचाने गए लक्षण",
    "Treatment Options": "उपचार विकल्प",
    "Chemical": "रासायनिक",
    "Organic": "जैविक",
    "Frequency": "आवृत्ति",
    "View Full Report": "पूर्ण रिपोर्ट देखें",
    "Scan Another": "दूसरा स्कैन करें",
    "Mark Complete": "पूर्ण चिह्नित करें",
    "High Priority": "उच्च प्राथमिकता",
    "Medium Priority": "मध्यम प्राथमिकता",
    "Low Priority": "कम प्राथमिकता",
    "My Crops": "मेरी फसलें",
    "+ Add Crop": "+ फसल जोड़ें",
    "Select / Switch Crop": "फसल चुनें / बदलें",
    "Please select a crop.": "कृपया एक फसल चुनें।",
    "Please enter the acreage for this crop.": "कृपया इस फसल के लिए रकबा दर्ज करें।",
    "Please select an irrigation system.": "कृपया एक सिंचाई प्रणाली चुनें।",
    "Please enter the sowing date.": "कृपया बुवाई की तारीख दर्ज करें।",
    "Example": "उदाहरण",
    "Full Scan Report": "पूरी स्कैन रिपोर्ट",
    "What This Means (In Simple Words)": "इसका क्या मतलब है (सरल शब्दों में)",
    "What the AI Noticed on Your Crop": "AI ने आपकी फसल में क्या देखा",
    "These are the exact signs the AI detected:": "ये वो संकेत हैं जो AI ने पकड़े:",
    "What To Do Right Now": "अभी क्या करें",
    "Follow these simple steps:": "इन आसान कदमों का पालन करें:",
    "AI Expert Recommendation": "AI विशेषज्ञ की सलाह",
    "Treatment Options": "उपचार के विकल्प",
    "Choose the one that works best for you:": "जो आपके लिए सबसे अच्छा हो वो चुनें:",
    "Chemical Treatment": "रासायनिक उपचार",
    "Available at any agri store. Fast-acting.": "किसी भी कृषि दुकान पर मिलता है। जल्दी असर करता है।",
    "Organic / Natural Treatment": "जैविक / प्राकृतिक उपचार",
    "Safer for soil. Slower but eco-friendly.": "मिट्टी के लिए सुरक्षित। धीमा लेकिन पर्यावरण अनुकूल।",
    "Keep Your Crop Healthy!": "अपनी फसल को स्वस्थ रखें!",
    "Add to Expenses": "खर्च में जोड़ें",
    "Receipt / Photo": "रसीद / फोटो",
    "✕ Remove Photo": "✕ फोटो हटाएं",
    "Windy": "हवादार",
    "Leaf Blight": "पत्ती का झुलसा",
    "Powdery Mildew": "चूर्णिल आसिता",
    "Root Rot": "जड़ सड़न",
    "Bacterial Wilt": "जीवाणु म्लानि",
    "Healthy Crop": "स्वस्थ फसल",
    "Iron Deficiency": "लोहे की कमी",
    "Moderate": "मध्यम",
    "Today’s Mandi Real-Time Rates": "आज के लाइव मंडी भाव",
    "Real sales reported by farmers in": "यहाँ के किसानों द्वारा दर्ज वास्तविक सौदे:",
    "Verified APMC Mandi Trade": "सत्यापित कृषि उपज मंडी व्यापार",
    "All Prices": "सभी मंडियां",
    "All Local Trades": "सभी स्थानीय सौदे",
    "Did you sell harvest in Mandi today?": "क्या आपने आज मंडी में फसल बेची?",
    "Record your actual sale to help fellow farmers in": "अन्य किसानों की मदद के लिए अपना बिक्री भाव दर्ज करें:",
    "Record Sale": "बिक्री दर्ज करें",
    "Record Mandi Harvest Sale": "मंडी फसल बिक्री दर्ज करें",
    "Crop Sold": "बेची गई फसल",
    "Selling Mandi": "बिक्री वाली मंडी",
    "Actual Selling Price per kg (₹)": "वास्तविक बिक्री दर प्रति किलो (₹)",
    "Quantity Sold": "बेची गई मात्रा",
    "Submit Real Mandi Trade": "वास्तविक मंडी व्यापार दर्ज करें",
    "Your mandi sale has been recorded and shared with nearby farmers!": "आपकी मंडी बिक्री सफलतापूर्वक दर्ज हो गई है!",
    "Net Farm Savings (शिल्लक बचत)": "शुद्ध कृषि बचत (शेष)",
    "Total Incomes (+ जमा)": "कुल आय (+ जमा)",
    "Total Expenses (- खर्च)": "कुल खर्च (- व्यय)",
    "Top Expenses Breakdown": "प्रमुख खर्चों का विवरण",
    "Income Sources Breakdown": "आय के स्रोतों का विवरण",
    "All Transactions": "सभी लेन-देन",
    "Incomes": "आय",
    "Expenses": "खर्च",
    "Log Farm Income": "कृषि आय दर्ज करें",
    "Log Farm Expense": "कृषि खर्च दर्ज करें",
    "Save Transaction": "लेन-देन सहेजें",
    "Active Market": "सक्रिय मंडी",
    "Govt. Regulated": "सरकारी विनियमित",
    "APMC Mandi Directory": "कृषि उपज मंडी निर्देशिका",
    "1 hour ago": "१ घंटे पहले",
    "3 hours ago": "३ घंटे पहले",
    "5 hours ago": "५ घंटे पहले",
    "Today, 10:45 AM": "आज, सुबह १०:४५",
    "Today, 08:30 AM": "आज, सुबह ०८:३०",
    "Today, 09:15 AM": "आज, सुबह ०९:१५",
    "Today, 11:00 AM": "आज, सुबह ११:००",
    "Just now": "अभी",
    "Ramtek APMC Mandi": "रामटेक एपीएमसी मंडी",
    "Nagpur APMC Mandi (Kalamna)": "नागपुर मंडी (कलमना)",
    "Hingna APMC Mandi": "हिंगना मंडी",
    "Kalmeshwar APMC Mandi": "कलमेश्वर मंडी",
    "Katol APMC Mandi": "काटोल मंडी",
    "Saoner APMC Mandi": "सावनेर मंडी",
    "Umred APMC Mandi": "उमरेड मंडी",
    "Mansar, Ramtek": "मनसर, रामटेक",
    "Ramtek": "रामटेक",
    "Saoner": "सावनेर",
    "Katol": "काटोल",
    "Umred": "उमरेड",
    "Tomato": "टमाटर",
    "Cotton": "कपास",
    "Cotton (Kapas)": "कपास",
    "Soybean": "सोयाबीन",
    "Wheat": "गेहूं",
    "Wheat (Sharbati)": "शरबती गेहूं",
    "Chilli": "मिर्च",
    "Green Chilli": "हरी मिर्च",
    "Nagpur Santra (Orange)": "नागपुर संतरा",
    "Orange": "संतरा",
    "Paddy / Rice": "धान / चावल",
    "Rice": "चावल",
    "Onion": "प्याज",
    "Gram": "चना",
    "Tur": "अरहर / तुअर",
    "Maize": "मक्का"
  },
  "mr": {
    "Home": "मुख्यपृष्ठ",
    "Farm": "शेत",
    "AI": "एआय",
    "More": "अधिक",
    "Crop Scanner": "पीक स्कॅनर",
    "AI Chat": "एआय चॅट",
    "Overview": "विहंगावलोकन",
    "Soil & Water": "माती आणि पाणी",
    "Crop History": "पीक इतिहास",
    "Farmer": "शेतकरी",
    "Rahul Desai": "राहुल देसाई",
    "Alex Mercer": "अ‍ॅलेक्स मर्सर",
    "Farm Operations Manager": "शेत व्यवस्थापक",
    "My Farm": "माझे शेत",
    "Nagpur, Maharashtra": "नागपूर, महाराष्ट्र",
    "Maharashtra": "महाराष्ट्र",
    "Nagpur": "नागपूर",
    "Day": "दिवस",
    "of": "पैकी",
    "irrigation": "सिंचन",
    "Wheat": "गहू",
    "Soybean": "सोयाबीन",
    "Cotton": "कापूस",
    "Rice": "तांदूळ",
    "Sugarcane": "ऊस",
    "Tomato": "टोमॅटो",
    "Onion": "कांदा",
    "Maize": "मका",
    "Chilli": "मिरची",
    "Groundnut": "भुईमूग",
    "Banana": "केळी",
    "Grapes": "द्राक्षे",
    "Other": "इतर",
    "Custom Crop": "कस्टम पीक",
    "Drip": "ठिबक सिंचन",
    "Water efficient, targeted": "पाण्याची बचत, अचूक",
    "Sprinkler": "तुषार सिंचन",
    "Overhead spray coverage": "हवेतून फवारणी",
    "Flood": "पारंपरिक पूर पद्धत",
    "Traditional surface flooding": "पारंपरिक पृष्ठभाग सिंचन",
    "Rain-fed": "कोरडवाहू (पावसावर आधारित)",
    "Depends on rainfall": "पावसावर अवलंबून",
    "Furrow": "सरी पद्धत",
    "Row-based channel system": "ओळ-आधारित नाली प्रणाली",
    "Borewell": "बोअरवेल",
    "Groundwater extraction": "भूजल उपसा",
    "Black Soil": "काळी माती",
    "Red Soil": "तांबडी माती",
    "Sandy Soil": "वाळूमिश्रित माती",
    "Loamy Soil": "गाळाची/चिकण माती",
    "Clay Soil": "चिकण माती",
    "Alluvial Soil": "गाळाची माती",
    "Well": "विहीर",
    "Canal": "कालवा",
    "River": "नदी",
    "Rainwater": "पावसाचे पाणी",
    "Tank": "तळे/टाकी",
    "Low": "कमी",
    "Medium": "मध्यम",
    "High": "जास्त",
    "Local APMC / Mandi": "स्थानिक कृषी उत्पन्न बाजार समिती (APMC)",
    "Sell to local wholesale market": "स्थानिक घाऊक बाजारात विक्री",
    "Contract Farming": "करार शेती (कॉन्ट्रॅक्ट फार्मिंग)",
    "Pre-agreed corporate buyer": "पूर्व-नियोजित खरेदीदार",
    "Direct to Consumer": "थेट ग्राहकाला विक्री",
    "Sell directly to local buyers": "स्थानिक ग्राहकांना थेट विक्री",
    "Acres": "एकर",
    "Hectares": "हेक्टर",
    "Register Your Crop": "तुमची पीक नोंदणी करा",
    "Select the crop you are currently growing": "सध्या घेत असलेले पीक निवडा",
    "Choose Your Crop": "तुमचे पीक निवडा",
    "Crop Details": "पिकाचे तपशील",
    "Sunlight: Full Sun": "सूर्यप्रकाश: पूर्ण ऊन",
    "Water Req: Medium": "पाण्याची गरज: मध्यम",
    "Growth Stages": "वाढीचे टप्पे",
    "Standard lifecycle": "मानक जीवन चक्र",
    "days": "दिवस",
    "📅 Expected Harvest:": "📅 अपेक्षित काढणी:",
    "Skip for now →": "आत्ता वगळा →",
    "Custom Crop Name *": "पिकाचे नाव लिहा *",
    "Variety / Name": "वाण / जात",
    "Field / Block Name": "शेत / ब्लॉकचे नाव",
    "Farm Location": "शेताचे ठिकाण",
    "Farm Address *": "शेताचा पत्ता *",
    "Area Allocation": "क्षेत्रफळ वाटप",
    "Total farm": "एकूण शेत",
    "Acreage for": "क्षेत्रफळ",
    "Irrigation System": "सिंचन पद्धत",
    "Sowing Schedule": "पेरणीचे वेळापत्रक",
    "Sowing Date *": "पेरणीची तारीख *",
    "Additional Notes": "अतिरिक्त नोंदी",
    "Select a crop to continue": "पुढे जाण्यासाठी पीक निवडा",
    "Register": "नोंदणी करा",
    "Data": "माहिती",
    "1. Farm Setup": "1. शेत सेटअप",
    "Register your land details": "तुमच्या जमिनीचे तपशील नोंदवा",
    "Basic Info": "मूलभूत माहिती",
    "Location": "स्थान",
    "State *": "राज्य *",
    "Map updates automatically based on your address": "नकाशा पत्त्यानुसार आपोआप अपडेट होतो",
    "Save Farm & Continue to Crop →": "शेत जतन करा आणि पीक नोंदवा →",
    "Farm Name *": "शेताचे नाव *",
    "Total Area *": "एकूण क्षेत्रफळ *",
    "Address Line 1": "पत्ता ओळ 1",
    "District *": "जिल्हा *",
    "Village/Town": "गाव / शहर",
    "Soil Type *": "मातीचा प्रकार *",
    "Water Availability": "पाण्याची उपलब्धता",
    "Primary Water Source": "प्राथमिक पाण्याचा स्रोत",
    "Preferred Market *": "पसंतीची बाजारपेठ *",
    "AgriFlow": "AgriFlow",
    "Welcome back": "पुन्हा स्वागत आहे",
    "Sign in to manage your farm's performance.": "शेताचे व्यवस्थापन करण्यासाठी साइन इन करा.",
    "Forgot password?": "पासवर्ड विसरलात?",
    "Don't have an account?": "खाते नाही?",
    "Login ->": "लॉगिन करा →",
    "Mobile Number": "मोबाइल नंबर",
    "Password or OTP": "पासवर्ड किंवा OTP",
    "← Back": "← मागे",
    "Create Account": "नवीन खाते तयार करा",
    "Join thousands of smart farmers": "हजारो स्मार्ट शेतकऱ्यांशी जोडा",
    "Already have an account?": "आधीच खाते आहे?",
    "Sign In": "साइन इन",
    "Farmer Name *": "शेतकऱ्याचे नाव *",
    "Mobile Number *": "मोबाइल नंबर *",
    "Location *": "स्थान *",
    "Password / OTP": "पासवर्ड / OTP",
    "Overall Farm Health": "एकूण शेतीचे आरोग्य",
    "Weather Context": "हवामानाचा अंदाज",
    "Quick Actions": "जलद कृती",
    "Today's Actions": "आजची कामे",
    "VIEW ALL": "सर्व पहा",
    "Progress": "प्रगती",
    "Details →": "तपशील →",
    "Register your crop to get personalized insights": "वैयक्तिक माहितीसाठी तुमची पीक नोंदणी करा",
    "Scan Crop": "पीक स्कॅन करा",
    "Farm Sensors": "शेत सेन्सर्स",
    "Add Expense": "खर्च जोडा",
    "Add Income": "उत्पन्न जोडा",
    "Daily Life": "दैनंदिन जीवन",
    "Life Cycle": "जीवन चक्र",
    "Good Morning": "शुभ सकाळ",
    "Good Afternoon": "शुभ दुपार",
    "Good Evening": "शुभ संध्याकाळ",
    "Farm Health": "शेताचे आरोग्य",
    "Health": "आरोग्य",
    "Growth": "वाढ",
    "Water": "पाणी",
    "Disease Risk": "रोगाचा धोका",
    "Good": "चांगले",
    "Excellent": "उत्कृष्ट",
    "Humidity": "हवेतील ओलावा (आर्द्रता)",
    "Rain": "पाऊस",
    "km/h": "किमी/तास",
    "Partly Cloudy": "अंशतः ढगाळ",
    "Sunny": "उन्हाळी/सूर्यप्रकाश",
    "Rainy": "पावसाळी",
    "Cloudy": "ढगाळ",
    "Stormy": "वादळी",
    "Clear": "स्वच्छ",
    "Crop Progress": "पिकाची प्रगती",
    "Sowing": "पेरणी",
    "Harvest": "काढणी",
    "Growth Performance": "वाढीची कामगिरी",
    "Stage": "टप्पा",
    "Germination": "अंकुरण",
    "Tillering": "फुटवे फुटणे",
    "Heading": "लोंब्या बाहेर पडणे",
    "Maturation": "पक्वता",
    "Vegetative": "शाकीय वाढ",
    "Flowering": "फुलधारणा",
    "Pod Formation": "शेंगा धरणे",
    "Squaring": "पात्या लागणे",
    "Boll Formation": "बोंड धरणे",
    "Nursery": "रोपवाटिका",
    "Transplanting": "पुनर्लागवड",
    "Panicle Initiation": "लोंब्यांची सुरुवात",
    "Planting": "लागवड",
    "Grand Growth": "जोरदार वाढ",
    "Fruit Set": "फळधारणा",
    "Bulb Formation": "कांदा/कंद भरणे",
    "Tasseling": "तुरा फुटणे",
    "Silking": "केस येणे",
    "Pegging": "आऱ्या सुटणे",
    "Pod Fill": "दाणे भरणे",
    "Shooting": "निसवणे",
    "Bunch Development": "घड भरणे",
    "Pruning": "छाटणी",
    "Budbreak": "कोंब फुटणे",
    "Shoot Growth": "शाखा वाढ",
    "Veraison": "फळात साखर भरणे",
    "Ask AgriFlow AI...": "AgriFlow AI ला विचारा...",
    "Thinking...": "विचार करत आहे...",
    "Suggested Questions": "सुचवलेले प्रश्न",
    "AI Crop Scanner": "AI पीक स्कॅनर",
    "Scan Your Crop": "तुमचे पीक स्कॅन करा",
    "Take or upload a photo of your crop to detect diseases with AI": "AI ने रोग शोधण्यासाठी पिकाचा फोटो घ्या किंवा अपलोड करा",
    "Analyzing crop...": "पिकाचे विश्लेषण सुरू आहे...",
    "AI is examining your crop for diseases": "AI तुमच्या पिकातील रोगांची तपासणी करत आहे",
    "Scan Results": "स्कॅन निकाल",
    "Take Photo": "फोटो काढा",
    "Upload Image": "चित्र अपलोड करा",
    "Upload": "अपलोड करा",
    "Loading...": "लोड होत आहे...",
    "Upload / Take Photo": "अपलोड करा / फोटो काढा",
    "✕ Remove": "✕ काढून टाका",
    "Camera": "कॅमेरा",
    "Gallery": "गॅलरी",
    "Live Analysis": "थेट विश्लेषण",
    "Analysis Result": "विश्लेषण निकाल",
    "Disease Detected": "आढळलेला रोग",
    "Leaf Blight": "पानावरील करपा (Leaf Blight)",
    "Confidence": "विश्वासार्हता",
    "Severity": "तीव्रता",
    "Action Plan": "कृती योजना",
    "Fertilizer Recommendation": "खत व्यवस्थापन शिफारस",
    "Precautions": "दक्षता आणि उपाय",
    "+ Add to Field Log": "+ शेत नोंदवहीत जोडा",
    "Recent Scans": "अलीकडील स्कॅन",
    "Field B - Corn": "शेत B - मका",
    "Healthy • 2h ago": "निरोगी • २ तासांपूर्वी",
    "Yield Prediction": "उत्पन्नाचा अंदाज",
    "Upcoming Tasks": "आगामी कामे",
    "Recent Activities": "अलीकडील कामे",
    "+ Register a Crop": "+ पीक नोंदवा",
    "No tasks yet. Add tasks to your farm diary.": "अजून कोणतेही काम नाही. डायरीत जोडा.",
    "No recent activities recorded.": "अलीकडे कोणतीही नोंद नाही.",
    "Register a crop to see yield prediction.": "उत्पन्न अंदाजासाठी पीक नोंदवा.",
    "Language Settings": "भाषा सेटिंग्ज",
    "Finance & Yield": "वित्त आणि उत्पन्न",
    "Farm Logistics": "शेती वाहतूक व रसद",
    "Intelligence & AI": "बुद्धिमत्ता आणि एआय",
    "System Hardware": "सिस्टम हार्डवेअर",
    "Select Language": "भाषा निवडा",
    "Choose your preferred language": "तुमची पसंतीची भाषा निवडा",
    "Save Language": "भाषा जतन करा",
    "Continue": "पुढे जा",
    "You can change this later in Settings": "तुम्ही हे नंतर सेटिंग्जमध्ये बदलू शकता",
    "Expense Type *": "खर्चाचा प्रकार *",
    "Amount & Date": "रक्कम आणि तारीख",
    "Payment Details": "पेमेंट तपशील",
    "Payment Mode": "पेमेंट पद्धत",
    "Amount (₹) *": "रक्कम (₹) *",
    "Date": "तारीख",
    "Paid To (Payee)": "कोणाला दिले",
    "Notes (Optional)": "नोंदी (पर्यायी)",
    "Expenses": "खर्च",
    "Filter": "फिल्टर",
    "Expense Distribution": "खर्चाचे वितरण",
    "All Expenses": "सर्व खर्च",
    "Income Type *": "उत्पन्नाचा प्रकार *",
    "Who & Why": "कोणाकडून आणि का",
    "Purpose / Reason": "उद्देश / कारण",
    "Amount": "रक्कम",
    "💡 Auto-calculate from quantity × price": "💡 प्रमाण × किंमत यावरून आपोआप गणना",
    "Calculated Amount": "गणना केलेली रक्कम",
    "From Whom (Source) *": "कोणाकडून (स्रोत) *",
    "Custom Purpose (Optional)": "कस्टम उद्देश (पर्यायी)",
    "Price/Unit (₹)": "किंमत/एकक (₹)",
    "Crop Lifecycle": "पीक जीवन चक्र",
    "Stage Details": "टप्प्याचे तपशील",
    "Care Schedule": "काळजीचे वेळापत्रक",
    "Daily Crop Life": "दैनंदिन पीक जीवन",
    "Select Day (0 – 5)": "दिवस निवडा (0 – 5)",
    "Document early germination stages with photos": "फोटोसह प्रारंभिक अंकुरण टप्पे नोंदवा",
    "Today's Conditions": "आजची परिस्थिती",
    "Past Entries": "मागील नोंदी",
    "Temp (°C)": "तापमान (°C)",
    "Humidity (%)": "आर्द्रता (%)",
    "Observation Note": "निरीक्षण नोंद",
    "Farm Diary": "शेत डायरी",
    "Farm Map": "शेताचा नकाशा",
    "Latitude": "अक्षांश",
    "Longitude": "रेखांश",
    "Village": "गाव",
    "District": "जिल्हा",
    "Map Legend": "नकाशा सूची",
    "Harvest Planning": "काढणी नियोजन",
    "Estimated Harvest Date": "अपेक्षित काढणी तारीख",
    "Harvest Readiness": "काढणीची तयारी",
    "Total Estimated Cost": "एकूण अंदाजित खर्च",
    "Planning Details": "नियोजन तपशील",
    "Cost Estimate": "खर्चाचा अंदाज",
    "Required Machinery": "आवश्यक यंत्रसामग्री",
    "Plan Harvest": "काढणीचे नियोजन करा",
    "View Storage Recommendation": "साठवणूक शिफारस पहा",
    "Smart Irrigation": "स्मार्ट सिंचन",
    "Soil Moisture Level": "मातीतील ओलाव्याची पातळी",
    "Estimated Water Required": "अंदाजित आवश्यक पाणी",
    "Current Status": "सध्याची स्थिती",
    "AI Recommendation": "AI ची शिफारस",
    "Actions": "कृती",
    "Schedule Irrigation": "सिंचन वेळापत्रक",
    "View Field Map": "शेताचा नकाशा पहा",
    "Planning & Logistics": "नियोजन आणि वाहतूक",
    "Optimize your upcoming harvest operations and supply chain routes.": "आगामी काढणी आणि पुरवठा साखळी मार्ग अनुकूल करा.",
    "Crop Readiness": "पीक तयारी",
    "RESOURCE REQUIREMENTS": "संसाधनांच्या गरजा",
    "Labor": "कामगार / मजूर",
    "Duration": "कालावधी",
    "Required Storage Volume": "आवश्यक साठवणूक क्षमता",
    "LOGISTICS ESTIMATE": "वाहतूक खर्च अंदाज",
    "Transport Cost": "वाहतूक खर्च",
    "Est. Fuel": "अंदाजित इंधन",
    "Farm Spatial Overview": "शेताचे स्थानिक विहंगावलोकन",
    "Loading market data...": "बाजार भाव लोड होत आहे...",
    "Market Intelligence": "बाजार माहिती व भाव",
    "Best Selling Period:": "सर्वोत्तम विक्री काळ:",
    "Price History — Last 6 Months": "भाव इतिहास — मागील ६ महिने",
    "Nearby Mandis": "जवळील कृषी उत्पन्न बाजार समित्या",
    "Notifications": "सूचना",
    "Plant Life Cycle": "वनस्पती जीवन चक्र",
    "General Crop Life Cycle": "सामान्य पीक जीवन चक्र",
    "Typical stages of plant development": "वनस्पती विकासाचे सामान्य टप्पे",
    "CURRENT STAGE": "सध्याचा टप्पा",
    "Expected Yield": "अपेक्षित उत्पन्न",
    "Total Quintals": "एकूण क्विंटल",
    "Risk Level": "जोखीम पातळी",
    "Prediction Confidence": "अंदाजाची अचूकता",
    "Production Projection": "उत्पादन अंदाज",
    "Influencing Factors": "प्रभाव पाडणारे घटक",
    "Registration successful!": "नोंदणी यशस्वी झाली!",
    "Please enter mobile number and password.": "कृपया मोबाइल नंबर आणि पासवर्ड टाका.",
    "Login failed. Try again.": "लॉगिन अयशस्वी. पुन्हा प्रयत्न करा.",
    "No data available": "माहिती उपलब्ध नाही",
    "Loading": "लोड होत आहे",
    "Save": "जतन करा",
    "Cancel": "रद्द करा",
    "Back": "मागे",
    "Submit": "सबमिट करा",
    "Next": "पुढे",
    "Done": "पूर्ण झाले",
    "Welcome to AgriFlow": "AgriFlow मध्ये आपले स्वागत आहे",
    "Empowering your agricultural journey with AI-driven insights and precision management.": "AI-आधारित माहिती आणि अचूक व्यवस्थापनासह तुमच्या शेती प्रवासाला सक्षम बनवणे.",
    "Get Started": "सुरू करा",
    "Log In": "लॉग इन",
    "since sowing": "पेरणीपासून",
    "Save Day Entry →": "नोंद जतन करा →",
    "Saved!": "जतन केले!",
    "Detection Confidence": "शोध विश्वासार्हता",
    "Symptoms Detected": "आढळलेली लक्षणे",
    "Treatment Options": "उपचार पर्याय",
    "Chemical": "रासायनिक",
    "Organic": "सेंद्रिय / जैविक",
    "Frequency": "वारंवारता",
    "View Full Report": "संपूर्ण अहवाल पहा",
    "Scan Another": "दुसरे स्कॅन करा",
    "Mark Complete": "पूर्ण झाले म्हणून खूण करा",
    "High Priority": "उच्च प्राधान्य",
    "Medium Priority": "मध्यम प्राधान्य",
    "Low Priority": "कमी प्राधान्य",
    "My Crops": "माझी पिके",
    "+ Add Crop": "+ पीक जोडा",
    "Select / Switch Crop": "पीक निवडा / बदला",
    "Please select a crop.": "कृपया एक पीक निवडा.",
    "Please enter the acreage for this crop.": "कृपया या पिकासाठी क्षेत्रफळ टाका.",
    "Please select an irrigation system.": "कृपया एक सिंचन पद्धत निवडा.",
    "Please enter the sowing date.": "कृपया पेरणीची तारीख टाका.",
    "Example": "उदाहरण",
    "Full Scan Report": "संपूर्ण स्कॅन अहवाल",
    "What This Means (In Simple Words)": "याचा अर्थ काय आहे (सोप्या भाषेत)",
    "What the AI Noticed on Your Crop": "AI ने तुमच्या पिकात काय पाहिले",
    "These are the exact signs the AI detected:": "AI ने शोधलेली ही चिन्हे आहेत:",
    "What To Do Right Now": "आत्ता काय करावे",
    "Follow these simple steps:": "हे सोपे उपाय करा:",
    "AI Expert Recommendation": "AI तज्ञांचा सल्ला",
    "Treatment Options": "उपचाराचे पर्याय",
    "Choose the one that works best for you:": "तुमच्यासाठी सर्वोत्तम पर्याय निवडा:",
    "Chemical Treatment": "रासायनिक उपचार",
    "Available at any agri store. Fast-acting.": "कोणत्याही कृषी दुकानात मिळते. लवकर परिणाम होतो.",
    "Organic / Natural Treatment": "सेंद्रिय / नैसर्गिक उपचार",
    "Safer for soil. Slower but eco-friendly.": "मातीसाठी सुरक्षित. हळू पण पर्यावरणपूरक.",
    "Keep Your Crop Healthy!": "तुमचे पीक निरोगी ठेवा!",
    "Add to Expenses": "खर्चात जोडा",
    "Receipt / Photo": "पावती / फोटो",
    "✕ Remove Photo": "✕ फोटो काढा",
    "Windy": "वारेसाठी",
    "Leaf Blight": "पानांचा करपा",
    "Powdery Mildew": "भुरी",
    "Root Rot": "मूळकूज",
    "Bacterial Wilt": "जिवाणूजन्य मर",
    "Healthy Crop": "निरोगी पीक",
    "Iron Deficiency": "लोहाची कमतरता",
    "Moderate": "मध्यम",
    "Today’s Mandi Real-Time Rates": "आजचे थेट बाजारभाव",
    "Real sales reported by farmers in": "येथील शेतकऱ्यांनी नोंदवलेले थेट सौदे:",
    "Verified APMC Mandi Trade": "प्रमाणित कृषी उत्पन्न बाजार समिती सौदा",
    "All Prices": "सर्व बाजार समित्या",
    "All Local Trades": "सर्व स्थानिक सौदे",
    "Did you sell harvest in Mandi today?": "तुम्ही आज बाजारात शेतमाल विकला का?",
    "Record your actual sale to help fellow farmers in": "इतर शेतकऱ्यांच्या मदतीसाठी तुमचा विक्री भाव नोंदवा:",
    "Record Sale": "बाजार भाव नोंदवा",
    "Record Mandi Harvest Sale": "बाजार समिती शेतमाल विक्री नोंदवा",
    "Crop Sold": "विकलेले पीक",
    "Selling Mandi": "विक्री केलेली बाजार समिती",
    "Actual Selling Price per kg (₹)": "प्रत्यक्ष विक्री दर प्रति किलो (₹)",
    "Quantity Sold": "विक्रीचे प्रमाण",
    "Submit Real Mandi Trade": "थेट बाजार सौदा जतन करा",
    "Your mandi sale has been recorded and shared with nearby farmers!": "तुमचा बाजार भाव यशस्वीरीत्या नोंदवला गेला आहे!",
    "Net Farm Savings (शिल्लक बचत)": "निव्वळ शेत बचत (शिल्लक)",
    "Total Incomes (+ जमा)": "एकूण उत्पन्न (+ जमा)",
    "Total Expenses (- खर्च)": "एकूण खर्च (- नावे)",
    "Top Expenses Breakdown": "प्रमुख खर्चांचे वर्गीकरण",
    "Income Sources Breakdown": "उत्पन्नाच्या स्रोतांचे वर्गीकरण",
    "All Transactions": "सर्व व्यवहार",
    "Incomes": "जमा उत्पन्न",
    "Expenses": "झालेला खर्च",
    "Log Farm Income": "शेती उत्पन्न नोंदवा",
    "Log Farm Expense": "शेती खर्च नोंदवा",
    "Save Transaction": "व्यवहार जतन करा",
    "Active Market": "सक्रिय बाजार समिती",
    "Govt. Regulated": "शासकीय मान्यताप्राप्त",
    "APMC Mandi Directory": "कृषी उत्पन्न बाजार समिती मार्गदर्शिका",
    "1 hour ago": "१ तासापूर्वी",
    "3 hours ago": "३ तासांपूर्वी",
    "5 hours ago": "५ तासांपूर्वी",
    "Today, 10:45 AM": "आज, सकाळी १०:४५",
    "Today, 08:30 AM": "आज, सकाळी ०८:३०",
    "Today, 09:15 AM": "आज, सकाळी ०९:१५",
    "Today, 11:00 AM": "आज, सकाळी ११:००",
    "Just now": "आत्ताच",
    "Ramtek APMC Mandi": "रामटेक कृषी उत्पन्न बाजार समिती",
    "Nagpur APMC Mandi (Kalamna)": "नागपूर बाजार समिती (कळमना)",
    "Hingna APMC Mandi": "हिंगणा बाजार समिती",
    "Kalmeshwar APMC Mandi": "कळमेश्वर बाजार समिती",
    "Katol APMC Mandi": "काटोल बाजार समिती",
    "Saoner APMC Mandi": "सावनेर बाजार समिती",
    "Umred APMC Mandi": "उमरेड बाजार समिती",
    "Mansar, Ramtek": "मनसर, रामटेक",
    "Ramtek": "रामटेक",
    "Saoner": "सावनेर",
    "Katol": "काटोल",
    "Umred": "उमरेड",
    "Tomato": "टोमॅटो",
    "Cotton": "कापूस",
    "Cotton (Kapas)": "कापूस",
    "Soybean": "सोयाबीन",
    "Wheat": "गहू",
    "Wheat (Sharbati)": "शरबती गहू",
    "Chilli": "मिरची",
    "Green Chilli": "हिरवी मिरची",
    "Nagpur Santra (Orange)": "नागपूर संत्रा",
    "Orange": "संत्रा",
    "Paddy / Rice": "धान / तांदूळ",
    "Rice": "तांदूळ",
    "Onion": "कांदा",
    "Gram": "हरभरा",
    "Tur": "तूर",
    "Maize": "मका"
  }
};

const LanguageContext = createContext(null);

// Comprehensive auto-translation for any key not found in the dictionary
const AUTO_TRANSLATE = {
  hi: {
    // Scan Report page
    'Full Scan Report': 'पूरी स्कैन रिपोर्ट',
    'Scan Results': 'स्कैन परिणाम',
    'What This Means (In Simple Words)': 'इसका मतलब (सरल शब्दों में)',
    'What the AI Noticed on Your Crop': 'AI ने आपकी फसल में क्या देखा',
    'These are the exact signs the AI detected:': 'ये वो संकेत हैं जो AI ने पकड़े:',
    'What To Do Right Now': 'अभी क्या करें',
    'Follow these simple steps:': 'इन आसान कदमों का पालन करें:',
    'AI Expert Recommendation': 'AI विशेषज्ञ की सलाह',
    'Choose the one that works best for you:': 'जो आपके लिए सबसे अच्छा हो वो चुनें:',
    'Chemical Treatment': 'रासायनिक उपचार',
    'Available at any agri store. Fast-acting.': 'किसी भी कृषि दुकान पर मिलता है। जल्दी असर करता है।',
    'Organic / Natural Treatment': 'जैविक / प्राकृतिक उपचार',
    'Safer for soil. Slower but eco-friendly.': 'मिट्टी के लिए सुरक्षित। धीमा लेकिन पर्यावरण अनुकूल।',
    'Keep Your Crop Healthy!': 'अपनी फसल को स्वस्थ रखें!',
    'Add to Expenses': 'खर्च में जोड़ें',
    'Receipt / Photo': 'रसीद / फोटो',
    '✕ Remove Photo': '✕ फोटो हटाएं',
    'The AI found signs of': 'AI ने लक्षण पाए',
    'on your crop. This is caused by a tiny organism. If you treat it quickly with the right medicine, your crop will recover well!': 'आपकी फसल पर। यह एक छोटे जीव की वजह से होता है। अगर आप सही दवाई से जल्दी इलाज करें, तो फसल ठीक हो जाएगी!',
    'The AI scanned your crop carefully and found no sign of disease. Your plants look strong and are growing normally. Just continue your regular care routine!': 'AI ने आपकी फसल को ध्यान से देखा और कोई बीमारी नहीं पाई। आपके पौधे मजबूत हैं और सामान्य रूप से बढ़ रहे हैं। अपनी नियमित देखभाल जारी रखें!',
    'Continue your regular watering schedule': 'अपनी नियमित सिंचाई जारी रखें',
    'Apply preventive neem spray every 3 weeks': 'हर 3 हफ्ते में नीम का रोकथाम स्प्रे करें',
    'Keep checking for early signs of disease': 'बीमारी के शुरुआती लक्षण देखते रहें',
    'Maintain proper spacing between plants': 'पौधों के बीच उचित दूरी बनाए रखें',
    'Buy': 'खरीदें',
    'from your local agri store': 'अपनी स्थानीय कृषि दुकान से',
    'Mix and spray on affected plants': 'प्रभावित पौधों पर मिलाकर स्प्रे करें',
    'Remove heavily damaged leaves before spraying': 'स्प्रे से पहले बुरी तरह क्षतिग्रस्त पत्तियां हटाएं',
    'Avoid watering plants from above — use drip irrigation': 'पौधों को ऊपर से पानी देने से बचें — ड्रिप सिंचाई का उपयोग करें',
    'Check progress every 3 days': 'हर 3 दिन में प्रगति जांचें',
    'Spray neem oil (3 mL per litre of water) every 3 weeks as a natural shield against future diseases. Always check the underside of leaves where pests hide first!': 'भविष्य की बीमारियों से बचाव के लिए हर 3 हफ्ते में नीम का तेल (3 मिली प्रति लीटर पानी) का स्प्रे करें। पत्तियों की निचली तरफ जरूर जांचें जहां कीट छिपते हैं!',
    'Act immediately! This disease can spread fast and damage your harvest.': 'तुरंत कार्रवाई करें! यह बीमारी तेजी से फैल सकती है और आपकी फसल को नुकसान पहुंचा सकती है।',
    'Take action within 2–3 days before this gets worse.': '2–3 दिनों में कार्रवाई करें वरना यह बढ़ सकता है।',
    'Keep an eye on your crop and treat if symptoms increase.': 'फसल पर नजर रखें और लक्षण बढ़ने पर इलाज करें।',
    'Your crop is in great shape! Keep up the good work.': 'आपकी फसल बहुत अच्छी है! इसी तरह देखभाल जारी रखें।',
    // Disease names
    'Leaf Blight': 'पत्ती का झुलसा',
    'Powdery Mildew': 'चूर्णिल आसिता',
    'Root Rot': 'जड़ सड़न',
    'Bacterial Wilt': 'जीवाणु म्लानि',
    'Healthy Crop': 'स्वस्थ फसल',
    'Iron Deficiency': 'लोहे की कमी',
    'No pathogen detected': 'कोई रोगाणु नहीं पाया गया',
    'Moderate': 'मध्यम',
    // Add Expense
    'Receipt / Photo': 'रसीद / फोटो',
    'Take Photo': 'फोटो लें',
    'Gallery': 'गैलरी',
    'Add Expense': 'खर्च जोड़ें',
    // Daily life
    'Windy': 'हवादार',
    'Save Day Entry →': 'दिन प्रविष्टि सहेजें →',
    'Day 0': 'दिन 0',
    'Day 1': 'दिन 1',
    'Day 2': 'दिन 2',
    'Day 3': 'दिन 3',
    'Day 4': 'दिन 4',
    'Day 5': 'दिन 5',
    'Sowing Day': 'बुवाई का दिन',
    // Lifecycle
    'Take Photo of Crop': 'फसल की फोटो लें',
    'Crop Health Analysis': 'फसल स्वास्थ्य विश्लेषण',
    'Precautions': 'सावधानियां',
    'Update required: Take a photo for the': 'अपडेट आवश्यक: इसके लिए फोटो लें -',
    'stage!': 'चरण!',
    'Upload Image': 'फोटो अपलोड करें',
    'Sowing Date': 'बुवाई की तारीख',
    'Expected Harvest': 'अपेक्षित कटाई',
    'Current Stage': 'वर्तमान चरण',
    'Completed': 'पूरा हुआ',
    'Upcoming': 'आगामी',
    'Days after sowing:': 'बुवाई के बाद के दिन:',
    'Start New Crop Lifecycle': 'नया फसल जीवन चक्र शुरू करें',
    'How would you like to start tracking?': 'आप ट्रैकिंग कैसे शुरू करना चाहेंगे?',
    'Enter Sowing Date': 'बुवाई की तारीख दर्ज करें',
    'I know when I sowed the seeds': 'मुझे पता है कि मैंने बीज कब बोए थे',
    'Scan Crop to Start': 'शुरू करने के लिए फसल स्कैन करें',
    'Let AI analyze your crop to determine the stage': 'AI को चरण निर्धारित करने के लिए आपकी फसल का विश्लेषण करने दें',
    'Start Tracking': 'ट्रैकिंग शुरू करें',
    'Start Date': 'शुरू करने की तारीख',
  },
  mr: {
    // Scan Report page
    'Full Scan Report': 'संपूर्ण स्कॅन अहवाल',
    'Scan Results': 'स्कॅन निकाल',
    'What This Means (In Simple Words)': 'याचा अर्थ काय आहे (सोप्या भाषेत)',
    'What the AI Noticed on Your Crop': 'AI ने तुमच्या पिकात काय पाहिले',
    'These are the exact signs the AI detected:': 'AI ने शोधलेली ही चिन्हे आहेत:',
    'What To Do Right Now': 'आत्ता काय करावे',
    'Follow these simple steps:': 'हे सोपे उपाय करा:',
    'AI Expert Recommendation': 'AI तज्ञांचा सल्ला',
    'Choose the one that works best for you:': 'तुमच्यासाठी सर्वोत्तम पर्याय निवडा:',
    'Chemical Treatment': 'रासायनिक उपचार',
    'Available at any agri store. Fast-acting.': 'कोणत्याही कृषी दुकानात मिळते. लवकर परिणाम होतो.',
    'Organic / Natural Treatment': 'सेंद्रिय / नैसर्गिक उपचार',
    'Safer for soil. Slower but eco-friendly.': 'मातीसाठी सुरक्षित. हळू पण पर्यावरणपूरक.',
    'Keep Your Crop Healthy!': 'तुमचे पीक निरोगी ठेवा!',
    'Add to Expenses': 'खर्चात जोडा',
    'Receipt / Photo': 'पावती / फोटो',
    '✕ Remove Photo': '✕ फोटो काढा',
    'The AI found signs of': 'AI ने लक्षणे आढळली',
    'on your crop. This is caused by a tiny organism. If you treat it quickly with the right medicine, your crop will recover well!': 'तुमच्या पिकात. हे एका सूक्ष्म जीवाणूमुळे होते. योग्य औषधाने लवकर उपचार केल्यास पीक बरे होईल!',
    'The AI scanned your crop carefully and found no sign of disease. Your plants look strong and are growing normally. Just continue your regular care routine!': 'AI ने तुमचे पीक काळजीपूर्वक तपासले आणि कोणताही रोग आढळला नाही. तुमची रोपे मजबूत आहेत आणि सामान्यपणे वाढत आहेत. तुमची नियमित काळजी सुरू ठेवा!',
    'Continue your regular watering schedule': 'तुमचे नियमित पाणी देणे सुरू ठेवा',
    'Apply preventive neem spray every 3 weeks': 'दर 3 आठवड्यांनी प्रतिबंधात्मक कडुनिंब फवारणी करा',
    'Keep checking for early signs of disease': 'रोगाची सुरुवातीची चिन्हे तपासत राहा',
    'Maintain proper spacing between plants': 'रोपांमधील योग्य अंतर ठेवा',
    'Buy': 'खरेदी करा',
    'from your local agri store': 'तुमच्या स्थानिक कृषी दुकानातून',
    'Mix and spray on affected plants': 'मिसळून बाधित रोपांवर फवारा',
    'Remove heavily damaged leaves before spraying': 'फवारणीपूर्वी जास्त खराब झालेली पाने काढा',
    'Avoid watering plants from above — use drip irrigation': 'वरून पाणी देणे टाळा — ठिबक सिंचन वापरा',
    'Check progress every 3 days': 'दर 3 दिवसांनी प्रगती तपासा',
    'Spray neem oil (3 mL per litre of water) every 3 weeks as a natural shield against future diseases. Always check the underside of leaves where pests hide first!': 'भविष्यातील रोगांपासून संरक्षणासाठी दर 3 आठवड्यांनी कडुनिंब तेल (3 मिली प्रति लिटर पाणी) फवारा. कीड लपते त्या पानांच्या खालच्या बाजूस नेहमी तपासा!',
    'Act immediately! This disease can spread fast and damage your harvest.': 'लगेच कार्यवाही करा! हा रोग वेगाने पसरू शकतो आणि तुमच्या पिकाचे नुकसान होऊ शकते.',
    'Take action within 2–3 days before this gets worse.': 'हे आणखी वाईट होण्यापूर्वी 2–3 दिवसांत उपाय करा.',
    'Keep an eye on your crop and treat if symptoms increase.': 'पिकावर लक्ष ठेवा आणि लक्षणे वाढल्यास उपचार करा.',
    'Your crop is in great shape! Keep up the good work.': 'तुमचे पीक उत्तम आहे! असेच काळजी घेत राहा.',
    // Disease names
    'Leaf Blight': 'पानांचा करपा',
    'Powdery Mildew': 'भुरी',
    'Root Rot': 'मूळकूज',
    'Bacterial Wilt': 'जिवाणूजन्य मर',
    'Healthy Crop': 'निरोगी पीक',
    'Iron Deficiency': 'लोहाची कमतरता',
    'No pathogen detected': 'कोणताही रोगजंतू आढळला नाही',
    'Moderate': 'मध्यम',
    // Add Expense
    'Receipt / Photo': 'पावती / फोटो',
    'Take Photo': 'फोटो घ्या',
    'Gallery': 'गॅलरी',
    'Add Expense': 'खर्च जोडा',
    // Daily life
    'Windy': 'वाऱ्याचे',
    'Save Day Entry →': 'नोंद जतन करा →',
    'Day 0': 'दिवस 0',
    'Day 1': 'दिवस 1',
    'Day 2': 'दिवस 2',
    'Day 3': 'दिवस 3',
    'Day 4': 'दिवस 4',
    'Day 5': 'दिवस 5',
    'Sowing Day': 'पेरणीचा दिवस',
    // Lifecycle
    'Take Photo of Crop': 'पिकाचा फोटो घ्या',
    'Crop Health Analysis': 'पीक आरोग्य विश्लेषण',
    'Precautions': 'खबरदारी',
    'Update required: Take a photo for the': 'अपडेट आवश्यक: यासाठी फोटो घ्या -',
    'stage!': 'टप्पा!',
    'Upload Image': 'फोटो अपलोड करा',
    'Sowing Date': 'पेरणीची तारीख',
    'Expected Harvest': 'अपेक्षित कापणी',
    'Current Stage': 'सध्याचा टप्पा',
    'Completed': 'पूर्ण झाले',
    'Upcoming': 'आगामी',
    'Days after sowing:': 'पेरणीनंतरचे दिवस:',
    'Start New Crop Lifecycle': 'नवीन पीक जीवन चक्र सुरू करा',
    'How would you like to start tracking?': 'तुम्ही ट्रॅकिंग कसे सुरू करू इच्छिता?',
    'Enter Sowing Date': 'पेरणीची तारीख प्रविष्ट करा',
    'I know when I sowed the seeds': 'मला माहित आहे की मी बियाणे कधी पेरले',
    'Scan Crop to Start': 'सुरू करण्यासाठी पीक स्कॅन करा',
    'Let AI analyze your crop to determine the stage': 'टप्पा निश्चित करण्यासाठी AI ला तुमच्या पिकाचे विश्लेषण करू द्या',
    'Start Tracking': 'ट्रॅकिंग सुरू करा',
    'Start Date': 'सुरुवातीची तारीख',
  }
};

// Technical terms that need English hint in brackets for non-English speakers
const TECHNICAL_BILINGUAL = new Set([
  'Confidence', 'Severity', 'Risk Level', 'Detection Confidence',
  'Leaf Blight', 'Powdery Mildew', 'Root Rot', 'Bacterial Wilt',
  'Iron Deficiency', 'Healthy Crop', 'Germination', 'Tillering',
  'Heading', 'Maturation', 'Vegetative', 'Flowering', 'Pod Formation',
  'Squaring', 'Boll Formation', 'Nursery', 'Transplanting',
  'Panicle Initiation', 'Grand Growth', 'Tasseling', 'Silking',
  'Pegging', 'Pod Fill', 'Veraison', 'Drip', 'Sprinkler',
  'Furrow', 'Borewell', 'Mancozeb', 'Metalaxyl', 'Fungicide',
  'Organic', 'Chemical', 'Frequency', 'Humidity', 'pH',
  'Alluvial Soil', 'Loamy Soil', 'Clay Soil', 'Sandy Soil',
  'APMC', 'Contract Farming', 'Yield Prediction', 'AI Recommendation',
  'Treatment Options', 'Symptoms Detected',
]);

// Simple human-friendly bilingual phrases
// Format: translated (English hint)
const BILINGUAL_HINTS = {
  hi: {
    'Confidence':            'सटीकता',
    'Severity':              'गंभीरता',
    'Risk Level':            'खतरे का स्तर',
    'Detection Confidence':  'पहचान कितनी सही है',
    'Leaf Blight':           'पत्ती का झुलसा रोग',
    'Powdery Mildew':        'सफ़ेद चूर्ण रोग',
    'Root Rot':              'जड़ सड़न रोग',
    'Bacterial Wilt':        'जीवाणु मुरझान रोग',
    'Iron Deficiency':       'लोहे की कमी',
    'Healthy Crop':          'स्वस्थ फसल',
    'Germination':           'अंकुरण',
    'Tillering':             'कल्ले फूटना',
    'Vegetative':            'पत्तियाँ बढ़ना',
    'Flowering':             'फूल आना',
    'Pod Formation':         'फली बनना',
    'Organic':               'जैविक / देसी',
    'Chemical':              'रासायनिक दवाई',
    'Frequency':             'कितनी बार करें',
    'Humidity':              'नमी',
    'Drip':                  'टपक सिंचाई',
    'Sprinkler':             'फुहारा सिंचाई',
    'Borewell':              'बोरवेल / ट्यूबवेल',
    'Yield Prediction':      'उपज का अनुमान',
    'AI Recommendation':     'AI की सलाह',
    'Treatment Options':     'उपचार के तरीके',
    'Symptoms Detected':     'बीमारी के लक्षण',
    'Alluvial Soil':         'जलोढ़ मिट्टी',
    'Loamy Soil':            'दोमट मिट्टी',
    'Clay Soil':             'चिकनी मिट्टी',
    'Contract Farming':      'कॉन्ट्रैक्ट खेती',
  },
  mr: {
    'Confidence':            'अचूकता',
    'Severity':              'तीव्रता',
    'Risk Level':            'धोक्याची पातळी',
    'Detection Confidence':  'ओळख किती बरोबर आहे',
    'Leaf Blight':           'पानांचा करपा',
    'Powdery Mildew':        'पांढरी भुरी',
    'Root Rot':              'मूळकूज',
    'Bacterial Wilt':        'जिवाणूजन्य मर',
    'Iron Deficiency':       'लोहाची कमतरता',
    'Healthy Crop':          'निरोगी पीक',
    'Germination':           'उगवण',
    'Tillering':             'फुटवे येणे',
    'Vegetative':            'पाने वाढणे',
    'Flowering':             'फुले येणे',
    'Pod Formation':         'शेंगा तयार होणे',
    'Organic':               'सेंद्रिय / नैसर्गिक',
    'Chemical':              'रासायनिक औषध',
    'Frequency':             'किती वेळा करायचे',
    'Humidity':              'ओलावा',
    'Drip':                  'ठिबक सिंचन',
    'Sprinkler':             'तुषार सिंचन',
    'Borewell':              'बोअरवेल',
    'Yield Prediction':      'उत्पादनाचा अंदाज',
    'AI Recommendation':     'AI चा सल्ला',
    'Treatment Options':     'उपचाराचे मार्ग',
    'Symptoms Detected':     'आजाराची लक्षणे',
    'Alluvial Soil':         'गाळाची माती',
    'Loamy Soil':            'मध्यम माती',
    'Clay Soil':             'चिकण माती',
    'Contract Farming':      'करारशेती',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const loadLang = async () => {
      try {
        const saved = await AsyncStorage.getItem(LANGUAGE_KEY);
        if (saved && DICTIONARY[saved]) {
          setLanguage(saved);
        }
      } catch (e) {}
    };
    loadLang();
  }, []);

  const changeLanguage = useCallback(async (lang) => {
    if (DICTIONARY[lang]) {
      setLanguage(lang);
      await AsyncStorage.setItem(LANGUAGE_KEY, lang);
    }
  }, []);

  const t = useCallback((key) => {
    if (!key) return '';

    // English — return as-is
    if (language === 'en') {
      return DICTIONARY['en']?.[key] || key;
    }

    // 1. Check main dictionary
    const dictResult = DICTIONARY[language]?.[key];
    // 2. Check auto-translate map
    const autoResult = AUTO_TRANSLATE[language]?.[key];

    const translated = dictResult || autoResult;

    if (translated) {
      // For technical terms, add English hint in brackets
      if (TECHNICAL_BILINGUAL.has(key) && BILINGUAL_HINTS[language]?.[key]) {
        return `${BILINGUAL_HINTS[language][key]} (${key})`;
      }
      return translated;
    }

    // 3. Fall back to English
    return DICTIONARY['en']?.[key] || key;
  }, [language]);

  // tb() = "translated bilingual" — always shows: LocalLang (English)
  // Use this for disease names, scientific terms shown prominently
  const tb = useCallback((key) => {
    if (!key) return key;
    if (language === 'en') return key;
    const hint = BILINGUAL_HINTS[language]?.[key];
    if (hint) return `${hint} (${key})`;
    const dictResult = DICTIONARY[language]?.[key] || AUTO_TRANSLATE[language]?.[key];
    if (dictResult) return `${dictResult} (${key})`;
    return key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, tb }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider');
  return ctx;
};
